port: 3000
sass:
    style: compressed

title: Brandon's Homepage
email: BrandonRoehl@gmail.com
description: >
 My personal website
 This also contains my blog
github_username: BrandonRoehl
twitter_username: BrandonRoehl
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/post-:year-:month-:day-:title.html

