port: 3000
sass:
    sass_dir: stylesheets
    style: compressed
permalink: /blog/post-:year-:month-:day-:title.html

title: Brandon's Homepage
email: BrandonRoehl@gmail.com
description: >
 Welcome to my blog!
github_username: BrandonRoehl
twitter_username: BrandonRoehl
defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

